## **Part.1: SCADI File**
### Datafile: SCADI.csv Data Description: This dataset contains 206 attributes of 70 children with physical and motor disability based on ICF-CY.


In [2]:
# Import important libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# to import the file from google drive, mount the drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
# load the dataset file and read the csv
folder_path = "/content/drive/MyDrive/MSDeakin/SIG720-MachineLearning/"
file_name = "SCADI.csv"

# Load the CSV file into a DataFrame
dataset = pd.read_csv(folder_path + file_name)

In [ ]:
#from google.colab import files

#file = files.upload()   # Upload a single file
#SCADI = list(file.keys())[0]  # Get the filename of the uploaded file
#df = pd.read_csv(SCADI, header=None)  # Read the CSV file into a DataFrame
#df.head()

Saving SCADI.csv to SCADI.csv


In [5]:
df = dataset.copy()
df.head()

Gender  Age  d 5100-0  d 5100-1  d 5100-2  d 5100-3  d 5100-4  d 5100-8  \
0       0   18         0         0         0         0         1         0   
1       0   22         0         0         0         0         1         0   
2       0   18         0         0         0         1         0         0   
3       1   18         0         0         0         0         1         0   
4       0   19         0         0         0         0         1         0   

   d 5100-9  d 5101-0  ...  d 57022-8  d 57022-9  d 571-0  d 571-1  d 571-2  \
0         0         0  ...          0          0        0        0        0   
1         0         0  ...          0          0        0        0        0   
2         0         0  ...          0          0        0        0        0   
3         0         0  ...          0          0        0        0        1   
4         0         0  ...          0          0        0        0        1   

   d 571-3  d 571-4  d 571-8  d 571-9  Classes  
0        0        1        0        0   class6  
1        1        0        0        0   class6  
2        1        0        0        0   class6  
3        0        0        0        0   class6  
4        0        0        0        0   class6  

[5 rows x 206 columns]

In [7]:
df.shape

(70, 206)

* dataset has 70 columns and 206 rows

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Columns: 206 entries, Gender to Classes
dtypes: int64(205), object(1)
memory usage: 112.8+ KB


* dataset has target variable as object datatype rest all are integer datatypes

In [9]:
df.describe().T

count       mean       std  min  25%   50%   75%   max
Gender     70.0   0.414286  0.496155  0.0  0.0   0.0   1.0   1.0
Age        70.0  12.257143  3.626336  6.0  9.0  12.0  15.0  22.0
d 5100-0   70.0   0.071429  0.259399  0.0  0.0   0.0   0.0   1.0
d 5100-1   70.0   0.142857  0.352454  0.0  0.0   0.0   0.0   1.0
d 5100-2   70.0   0.271429  0.447907  0.0  0.0   0.0   1.0   1.0
...         ...        ...       ...  ...  ...   ...   ...   ...
d 571-2    70.0   0.314286  0.467583  0.0  0.0   0.0   1.0   1.0
d 571-3    70.0   0.157143  0.366563  0.0  0.0   0.0   0.0   1.0
d 571-4    70.0   0.085714  0.281963  0.0  0.0   0.0   0.0   1.0
d 571-8    70.0   0.000000  0.000000  0.0  0.0   0.0   0.0   0.0
d 571-9    70.0   0.000000  0.000000  0.0  0.0   0.0   0.0   0.0

[205 rows x 8 columns]

### **1. Determine the number of subgroups from the dataset using attributes 3 to 205 i.e., exclude attributes 1, 2 and 206. Is this number the same as the number of classes presented by attribute 206? Explain and justify your findings.**

In [11]:
# Exclude attributes 1, 2, and 206
attributes_3_to_205 = df.iloc[:, 2:206]

# Determine the number of subgroups
num_subgroups = len(attributes_3_to_205.drop_duplicates())

In [16]:
# Check the number of classes presented by attribute 206
num_classes_attribute_206 = len(df['Classes'].unique())

print(f"Number of subgroups from attributes 3 to 205: {num_subgroups}")
print(f"Number of classes presented by attribute 206: {num_classes_attribute_206}")


Number of subgroups from attributes 3 to 205: 70
Number of classes presented by attribute 206: 7


* The number of subgroups presented in the attributes from 3 to 205 is 70 whereas in attribute 206 'Classes' is 7.

### **2. Is this data facing the curse of dimensionality? If so, then how to solve this problem. Explain with a two-dimensional plot and report relevant loss of information.**

In [8]:
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
# importing ploting libraries
import matplotlib.pyplot as plt
from scipy.stats import zscore
from sklearn import datasets
%matplotlib inline

In [6]:
# Extract features (all columns except the last one)
X = df.iloc[:, :-1]
y = df.Classes

In [9]:
#Normalize the data
X_std = StandardScaler().fit_transform(X)

In [10]:
#Calculate the covariance matrix
cov_matrix = np.cov(X_std.T)
print('Covariance Matrix \n%s', cov_matrix)

Covariance Matrix 
%s [[ 1.01449275 -0.22437261  0.10607907 ...  0.0540499   0.
   0.        ]
 [-0.22437261  1.01449275 -0.23891833 ...  0.04971153  0.
   0.        ]
 [ 0.10607907 -0.23891833  1.01449275 ... -0.08615151  0.
   0.        ]
 ...
 [ 0.0540499   0.04971153 -0.08615151 ...  1.01449275  0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 0.          0.          0.         ...  0.          0.
   0.        ]]


In [ ]:
#Calculate the eigenvalues and eigenvectors
eig_vals, eig_vecs = np.linalg.eig(cov_matrix)

print('Eigen Vectors \n%s', eig_vecs)
print('\n Eigen Values \n%s', eig_vals)

In [ ]:
eigen_pairs = [(np.abs(eig_vals[i]), eig_vecs[ :, i]) for i in range(len(eig_vals))]


tot = sum(eig_vals)
var_exp = [( i /tot ) * 100 for i in sorted(eig_vals, reverse=True)]
cum_var_exp = np.cumsum(var_exp)
print("Cumulative Variance Explained", cum_var_exp)


plt.figure(figsize=(6 , 4))
plt.bar(range(4), var_exp, alpha = 0.5, align = 'center', label = 'Individual explained variance')
plt.step(range(4), cum_var_exp, where='mid', label = 'Cumulative explained variance')
plt.ylabel('Explained Variance Ratio')
plt.xlabel('Principal Components')
plt.legend(loc = 'best')
plt.tight_layout()
plt.show()

In [ ]:
# Apply PCA for dimensionality reduction to 2 components
pca = PCA(n_components=2)
reduced_data = pca.fit_transform(attributes_3_to_205)

# Create a scatter plot to visualize the reduced data
plt.scatter(reduced_data[:, 0], reduced_data[:, 1])
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.title('PCA: 2D plot of reduced data')
plt.show()

### **3. After applying principal component analysis (PCA) on a given dataset, it was found that the percentage of variance for the first N components is X%. How is this percentage of variance computed?**

In [ ]:
# Obtain the percentage of variance explained by each principal component
variance_explained = pca.explained_variance_ratio_

print(f"Percentage of variance explained by the first component: {variance_explained[0]*100:.2f}%")
print(f"Percentage of variance explained by the second component: {variance_explained[1]*100:.2f}%")


## **Part2. Obseity File**

### Dataset filename: obesity_levels.csv.
### Dataset description: This dataset includes data for the estimation of obesity levels in individuals based on their eating habits and physical condition. The data contains 17 attributes and 2111 records.

### Features and labels: The attribute names are listed below. The description of the attributes can be found in this article.

### Create a machine learning (ML) model for predicting “weight” using all features except “NObeyesdad” and report observed performance.

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [ ]:
# load the dataset file and read the csv
folder_path = "/content/drive/MyDrive/MSDeakin/SIG720-MachineLearning/"
file_name = "ObesityDataSet.csv"

# Load the CSV file into a DataFrame
dataset2 = pd.read_csv(folder_path + file_name)

In [ ]:
df2 = dataset2.copy()
df2.head()

0    1       2       3                               4     5     6   \
0  Gender  Age  Height  Weight  family_history_with_overweight  FAVC  FCVC   
1  Female   21    1.62      64                             yes    no     2   
2  Female   21    1.52      56                             yes    no     3   
3    Male   23     1.8      77                             yes    no     2   
4    Male   27     1.8      87                              no    no     3   

    7          8      9     10   11   12   13          14  \
0  NCP       CAEC  SMOKE  CH2O  SCC  FAF  TUE        CALC   
1    3  Sometimes     no     2   no    0    1          no   
2    3  Sometimes    yes     3  yes    3    0   Sometimes   
3    3  Sometimes     no     2   no    2    1  Frequently   
4    3  Sometimes     no     2   no    2    0  Frequently   

                      15                  16  
0                 MTRANS          NObeyesdad  
1  Public_Transportation       Normal_Weight  
2  Public_Transportation       Normal_Weight  
3  Public_Transportation       Normal_Weight  
4                Walking  Overweight_Level_I

In [ ]:
# Remove the 'NObeyesdad' column from features and set 'weight' as the target variable
X = df.drop([3,16], axis=1)
y = df[3]


In [ ]:
X.head()

0    1       2                               4     5     6    7   \
0  Gender  Age  Height  family_history_with_overweight  FAVC  FCVC  NCP   
1  Female   21    1.62                             yes    no     2    3   
2  Female   21    1.52                             yes    no     3    3   
3    Male   23     1.8                             yes    no     2    3   
4    Male   27     1.8                              no    no     3    3   

          8      9     10   11   12   13          14                     15  
0       CAEC  SMOKE  CH2O  SCC  FAF  TUE        CALC                 MTRANS  
1  Sometimes     no     2   no    0    1          no  Public_Transportation  
2  Sometimes    yes     3  yes    3    0   Sometimes  Public_Transportation  
3  Sometimes     no     2   no    2    1  Frequently  Public_Transportation  
4  Sometimes     no     2   no    2    0  Frequently                Walking

In [ ]:
y.head()

0    Weight
1        64
2        56
3        77
4        87
Name: 3, dtype: object

In [ ]:
# Perform label encoding or one-hot encoding for text variables in X if needed

# Split the data into training and testing sets (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Create and train the Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

In [ ]:
# Make predictions on the test data
y_pred = model.predict(X_test)

# Evaluate the model's performance
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)